name: CSS Workflow
on:
  push:
    branches:
      - main  # Change this to your branch name if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Build CSS
      run: |
        # Replace `path/to/your/css/file.css` with the actual path to your CSS file
        npx postcss path/to/your/css/file.css -o dist/style.css
